"""Add template_id to workouts table

Revision ID: 3736e8f8d616
Revises: 613bb64584f3
Create Date: 2025-12-09 19:02:03.149969

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3736e8f8d616"
down_revision: Union[str, None] = "613bb64584f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("template_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_workouts_template_id"), "workouts", ["template_id"], unique=False
    )
    op.create_foreign_key(
        "fk_workouts_template_id", "workouts", "templates", ["template_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workouts_template_id", "workouts", type_="foreignkey")
    op.drop_index(op.f("ix_workouts_template_id"), table_name="workouts")
    op.drop_column("workouts", "template_id")
    # ### end Alembic commands ###
