"""Add firebase_uid and user_id foreign keys

Revision ID: c54a91116625
Revises: b053abf46c2e
Create Date: 2025-12-02 16:08:10.914878

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c54a91116625"
down_revision: Union[str, None] = "b053abf46c2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_templates_user_id"), "templates", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_templates_user_id", "templates", "users", ["user_id"], ["id"]
    )
    op.add_column("training_plans", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_training_plans_user_id"), "training_plans", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_training_plans_user_id", "training_plans", "users", ["user_id"], ["id"]
    )
    op.add_column("users", sa.Column("firebase_uid", sa.String(), nullable=False))
    op.create_index(
        op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True
    )
    op.add_column("workouts", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    op.create_foreign_key(
        "fk_workouts_user_id", "workouts", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.drop_index(op.f("ix_workouts_user_id"), table_name="workouts")
    op.drop_column("workouts", "user_id")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_column("users", "firebase_uid")
    op.drop_constraint(None, "training_plans", type_="foreignkey")
    op.drop_index(op.f("ix_training_plans_user_id"), table_name="training_plans")
    op.drop_column("training_plans", "user_id")
    op.drop_constraint(None, "templates", type_="foreignkey")
    op.drop_index(op.f("ix_templates_user_id"), table_name="templates")
    op.drop_column("templates", "user_id")
    # ### end Alembic commands ###
